#!/usr/bin/env python3
"""Pilot batch: attach a verified YouTube longplay link + AI-generated tags
to a handful of well-known NES titles, to prove the enrichment pipeline
before scaling to the rest of the 175K-game catalog.
"""
import os
import sqlite3

DB_PATH = os.path.join(os.path.dirname(__file__), "games.db")

# youtube_link: found via real web search (WebSearch tool), each title
# explicitly labeled "no commentary" / "longplay" by its uploader.
# tags: generated by the assistant from game knowledge (genre, mechanics, mood).
PILOT = {
    "Bubble Bobble": {
        "youtube_link": "https://www.youtube.com/watch?v=H1oDlqYfTmc",
        "tags": ["puzzle-platformer", "co-op", "cute", "arcade-port", "single-screen", "classic"],
    },
    "Castlevania": {
        "youtube_link": "https://www.youtube.com/watch?v=b41PkuzeS7A",
        "tags": ["gothic", "action-platformer", "horror", "difficult", "whip-combat", "classic", "atmospheric"],
    },
    "Double Dragon": {
        "youtube_link": "https://www.youtube.com/watch?v=QV5eUdaid18",
        "tags": ["beat-em-up", "brawler", "co-op", "arcade-port", "martial-arts", "classic"],
    },
    "Final Fantasy": {
        "youtube_link": "https://www.youtube.com/watch?v=A6sdvTUh9II",
        "tags": ["jrpg", "turn-based", "fantasy", "party-based", "classic", "story-rich"],
    },
    "Kirby's Adventure": {
        "youtube_link": "https://www.youtube.com/watch?v=3jt__MP4IzE",
        "tags": ["platformer", "cute", "copy-ability", "casual-friendly", "colorful", "classic"],
    },
    "Metroid": {
        "youtube_link": "https://www.youtube.com/watch?v=uojXYVy97Cc",
        "tags": ["metroidvania", "sci-fi", "exploration", "atmospheric", "nonlinear", "classic"],
    },
    "Super Mario Bros. 3": {
        "youtube_link": "https://www.youtube.com/watch?v=zFkiDdvy7Ds",
        "tags": ["platformer", "classic", "power-ups", "world-map", "colorful", "iconic"],
    },
    "Tetris": {
        "youtube_link": "https://www.youtube.com/watch?v=48SwZB9yvH0",
        "tags": ["puzzle", "falling-blocks", "classic", "single-player", "high-score-chase", "iconic"],
    },
    "The Legend of Zelda": {
        "youtube_link": "https://www.youtube.com/watch?v=QjYKrbAlAS0",
        "tags": ["action-adventure", "fantasy", "exploration", "dungeon-crawling", "nonlinear", "classic", "iconic"],
    },
}


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON")

    updated = 0
    for title, info in PILOT.items():
        row = conn.execute(
            "SELECT id FROM games WHERE title = ? AND platform = 'the NES'", (title,)
        ).fetchone()
        if not row:
            print(f"WARNING: no exact match for {title!r}, skipping")
            continue
        game_id = row[0]

        conn.execute("UPDATE games SET youtube_link = ? WHERE id = ?", (info["youtube_link"], game_id))

        for tag in info["tags"]:
            conn.execute("INSERT OR IGNORE INTO tags (name) VALUES (?)", (tag,))
            tag_id = conn.execute("SELECT id FROM tags WHERE name = ?", (tag,)).fetchone()[0]
            conn.execute(
                "INSERT OR IGNORE INTO game_tags (game_id, tag_id) VALUES (?, ?)", (game_id, tag_id)
            )
        updated += 1

    conn.commit()
    print(f"Updated {updated}/{len(PILOT)} pilot games with youtube_link + tags.")
    conn.close()


if __name__ == "__main__":
    main()
