// Generated by scripts/generate-atari-5200-catalog.mjs. Do not edit by hand.
// Sources:
// - https://en.wikipedia.org/wiki/List_of_Atari_5200_games
// Retrieved: 2026-07-06T15:28:17.679Z

import type { Game } from "./games";

type GeneratedGameMetadata = Omit<Game, "playthroughUrl">;

export type Atari5200CatalogRegion = keyof typeof regionLabels;
export type Atari5200CatalogSourceCategory = "licensed" | "unreleased";

export type Atari5200CatalogGame = GeneratedGameMetadata & {
  sourceCategory: Atari5200CatalogSourceCategory;
  developer: string[];
  publisher: string[];
  regions: string[];
  firstReleased: string;
  format?: string;
  sourceUrl: string;
  generatedAt: string;
  signalScore: number;
};

export const regionLabels = {
  "NA": "North America",
  "unreleased": "Unreleased"
} as const;

export const atari5200CatalogSource = {
  "name": "Wikipedia Atari 5200 catalog tables",
  "retrievedAt": "2026-07-06T15:28:17.679Z",
  "rowCount": 101,
  "sourceCounts": {
    "licensed": 69,
    "unreleased": 32
  },
  "sources": [
    {
      "name": "Wikipedia: List of Atari 5200 games",
      "url": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games"
    }
  ]
} as const;

export const generatedAtari5200Games: Atari5200CatalogGame[] = [
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "October 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "asteroids",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Asteroids is an unreleased Atari 5200 project from 1982, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Asteroids",
    "year": "1982"
  },
  {
    "developer": [
      "First Star Software"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "astro-chase",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Astro Chase is an Atari 5200 release from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "overhead"
    ],
    "title": "Astro Chase",
    "year": "1983"
  },
  {
    "developer": [
      "Lucasfilm Games"
    ],
    "difficulty": "fair",
    "firstReleased": "1986",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "ballblazer",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Ballblazer is an Atari 5200 release from 1986, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Atari Corp."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Ballblazer",
    "year": "1986"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "barroom-baseball",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Barroom Baseball is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 2,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "overhead",
      "sports",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Barroom Baseball",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "December 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "battlezone",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Battlezone is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Battlezone",
    "year": "1983"
  },
  {
    "developer": [
      "Action Graphics"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "beamrider",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Beamrider is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Beamrider",
    "year": "1984"
  },
  {
    "developer": [
      "GCC"
    ],
    "difficulty": "fair",
    "firstReleased": "February 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "berzerk",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Berzerk is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Berzerk",
    "year": "1984"
  },
  {
    "developer": [
      "Solitaire Group"
    ],
    "difficulty": "casual",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "blue-print",
    "isRomhack": false,
    "moods": [
      "contemplative",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Blue Print is an Atari 5200 release from 1983, tagged as approachable, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action",
      "board and card"
    ],
    "title": "Blue Print",
    "year": "1983"
  },
  {
    "developer": [
      "Big Five Software"
    ],
    "difficulty": "fair",
    "firstReleased": "April 1985",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "bounty-bob-strikes-back",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Bounty Bob Strikes Back! is an Atari 5200 release from 1985, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Big Five Software"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "overhead"
    ],
    "title": "Bounty Bob Strikes Back!",
    "year": "1985"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "December 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "bristles",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Bristles is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "First Star Software"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "overhead",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Bristles",
    "year": "1983"
  },
  {
    "developer": [
      "Sega"
    ],
    "difficulty": "fair",
    "firstReleased": "November 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "buck-rogers-planet-of-zoom",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Buck Rogers: Planet of Zoom is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Sega"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Buck Rogers: Planet of Zoom",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "February 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "centipede",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "classic",
    "pitch": "Centipede is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Centipede",
    "year": "1983"
  },
  {
    "developer": [
      "GCC"
    ],
    "difficulty": "fair",
    "firstReleased": "May 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "choplifter",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Choplifter is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Choplifter",
    "year": "1984"
  },
  {
    "developer": [
      "Sega"
    ],
    "difficulty": "fair",
    "firstReleased": "December 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "congo-bongo",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Congo Bongo is an Atari 5200 release from 1983, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Sega"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Congo Bongo",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "February 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "countermeasure",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Countermeasure is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Countermeasure",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "difficult",
    "firstReleased": "December 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "defender",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "classic",
    "pitch": "Defender is an Atari 5200 release from 1982, tagged as demanding, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Defender",
    "year": "1982"
  },
  {
    "developer": [
      "GCC"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "dig-dug",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Dig Dug is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Dig Dug",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "First Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "domino-man",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Domino Man is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Domino Man",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "November 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "fathom",
    "isRomhack": false,
    "moods": [
      "weird",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Fathom is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Imagic"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Fathom",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "difficult",
    "firstReleased": "Third Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "final-legacy",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Final Legacy is an unreleased Atari 5200 project from 1984, tagged as demanding, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 2,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Final Legacy",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "Third Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "flip-and-flop",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Flip and Flop is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "First Star Software"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 2,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "overhead",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Flip and Flop",
    "year": "1984"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "fair",
    "firstReleased": "June 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "frogger",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Frogger is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Frogger",
    "year": "1983"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "fair",
    "firstReleased": "September 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "frogger-ii-threeedeep",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Frogger II: ThreeeDeep! is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Frogger II: ThreeeDeep!",
    "year": "1984"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "October 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "galaxian",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Galaxian is an Atari 5200 release from 1982, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Galaxian",
    "year": "1982"
  },
  {
    "developer": [
      "Roklan Corporation"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "gorf",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Gorf is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Gorf",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "1986",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "gremlins",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Gremlins is an Atari 5200 release from 1986, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari Corp."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Gremlins",
    "year": "1986"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "fair",
    "firstReleased": "June 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "gyruss",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Gyruss is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Gyruss",
    "year": "1984"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "August 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "h-e-r-o",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "H.E.R.O. is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "H.E.R.O.",
    "year": "1984"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "fair",
    "firstReleased": "May 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "james-bond-007",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "James Bond 007 is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "James Bond 007",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "June 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "jawbreaker",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Jawbreaker is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Sierra On-Line"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Jawbreaker",
    "year": "1984"
  },
  {
    "developer": [
      "GCC"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "joust",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Joust is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Joust",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "September 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "jungle-hunt",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Jungle Hunt is an Atari 5200 release from 1983, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Jungle Hunt",
    "year": "1983"
  },
  {
    "developer": [
      "K-Byte"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "k-razy-shoot-out",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "K-Razy Shoot-Out is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action",
      "shooter"
    ],
    "title": "K-Razy Shoot-Out",
    "year": "1983"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "November 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "kaboom",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Kaboom! is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Kaboom!",
    "year": "1983"
  },
  {
    "developer": [
      "GCC"
    ],
    "difficulty": "fair",
    "firstReleased": "August 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "kangaroo",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Kangaroo is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Kangaroo",
    "year": "1983"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "June 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "keystone-kapers",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Keystone Kapers is an Atari 5200 release from 1984, tagged as balanced, story-forward, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 3,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "rich",
    "tags": [
      "NA exclusive",
      "adventure",
      "rpg"
    ],
    "title": "Keystone Kapers",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "December 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "laser-gates",
    "isRomhack": false,
    "moods": [
      "weird",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Laser Gates is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Imagic"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Laser Gates",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "December 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "madden-football",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Madden Football is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 2,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "overhead",
      "sports",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Madden Football",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "February 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "mario-bros",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Mario Bros. is an Atari 5200 release from 1984, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Mario Bros.",
    "year": "1984"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "February 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "megamania",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Megamania is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Megamania",
    "year": "1984"
  },
  {
    "developer": [
      "Electra Concepts"
    ],
    "difficulty": "fair",
    "firstReleased": "July 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "meteorites",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Meteorites is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Electra Concepts"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Meteorites",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "Third Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "millipede",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Millipede is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Millipede",
    "year": "1984"
  },
  {
    "developer": [
      "Big Five Software"
    ],
    "difficulty": "fair",
    "firstReleased": "July 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "miner-2049er",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Miner 2049er is an Atari 5200 release from 1983, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Big Five Software"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "overhead"
    ],
    "title": "Miner 2049er",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "difficult",
    "firstReleased": "October 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "missile-command",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "classic",
    "pitch": "Missile Command is an Atari 5200 release from 1982, tagged as demanding, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Missile Command",
    "year": "1982"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "fair",
    "firstReleased": "September 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "montezuma-s-revenge",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Montezuma's Revenge is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Montezuma's Revenge",
    "year": "1984"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "December 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "moon-patrol",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Moon Patrol is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Moon Patrol",
    "year": "1983"
  },
  {
    "developer": [
      "K-Byte"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "mountain-king",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Mountain King is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Mountain King",
    "year": "1983"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "mr-do-s-castle",
    "isRomhack": false,
    "moods": [
      "arcade",
      "ominous"
    ],
    "obscurity": "strange",
    "pitch": "Mr. Do's Castle is an Atari 5200 release from 1984, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Mr. Do's Castle",
    "year": "1984"
  },
  {
    "developer": [
      "GCC"
    ],
    "difficulty": "casual",
    "firstReleased": "September 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "ms-pac-man",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Ms. Pac-Man is an Atari 5200 release from 1983, tagged as approachable, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action",
      "arcade port"
    ],
    "title": "Ms. Pac-Man",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "casual",
    "firstReleased": "November 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "pac-man",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "classic",
    "pitch": "Pac-Man is an Atari 5200 release from 1982, tagged as approachable, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action",
      "arcade port"
    ],
    "title": "Pac-Man",
    "year": "1982"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "Fourth Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "pastfinder",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Pastfinder is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Pastfinder",
    "year": "1984"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "December 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "pengo",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Pengo is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Pengo",
    "year": "1983"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "September 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "pitfall-ii-lost-caverns",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Pitfall II: Lost Caverns is an Atari 5200 release from 1984, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Pitfall II: Lost Caverns",
    "year": "1984"
  },
  {
    "developer": [
      "Beck-Tech"
    ],
    "difficulty": "fair",
    "firstReleased": "March 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "pitfall",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Pitfall! is an Atari 5200 release from 1984, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Pitfall!",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "November 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "polaris",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Polaris is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Tigervision"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Polaris",
    "year": "1983"
  },
  {
    "developer": [
      "GCC"
    ],
    "difficulty": "fair",
    "firstReleased": "September 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "pole-position",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Pole Position is an Atari 5200 release from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Pole Position",
    "year": "1983"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "fair",
    "firstReleased": "November 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "popeye",
    "isRomhack": false,
    "moods": [
      "heroic",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Popeye is an Atari 5200 release from 1983, tagged as balanced, lightly narrative, and action adventure-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "action-adventure",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 3,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "some",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Popeye",
    "year": "1983"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "casual",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "q-bert",
    "isRomhack": false,
    "moods": [
      "contemplative",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Q*bert is an Atari 5200 release from 1983, tagged as approachable, play-first, and puzzle-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "puzzle",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 3,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Q*bert",
    "year": "1983"
  },
  {
    "developer": [
      "GCC"
    ],
    "difficulty": "casual",
    "firstReleased": "March 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "qix",
    "isRomhack": false,
    "moods": [
      "contemplative",
      "arcade"
    ],
    "obscurity": "classic",
    "pitch": "Qix is an Atari 5200 release from 1983, tagged as approachable, play-first, and puzzle-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "puzzle",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 3,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Qix",
    "year": "1983"
  },
  {
    "developer": [
      "VSS",
      "Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "December 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "quest-for-quintana-roo",
    "isRomhack": false,
    "moods": [
      "heroic",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Quest for Quintana Roo is an Atari 5200 release from 1984, tagged as balanced, lightly narrative, and action adventure-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "action-adventure",
    "publisher": [
      "Sunrise Software",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 3,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "some",
    "tags": [
      "NA exclusive",
      "adventure"
    ],
    "title": "Quest for Quintana Roo",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "November 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "quick-step",
    "isRomhack": false,
    "moods": [
      "weird",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Quick Step is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Imagic"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Quick Step",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "realsports-baseball",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "RealSports Baseball is an Atari 5200 release from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "overhead",
      "sports"
    ],
    "title": "RealSports Baseball",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "realsports-basketball",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "RealSports Basketball is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 2,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "overhead",
      "sports",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "RealSports Basketball",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "December 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "realsports-football",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "RealSports Football is an Atari 5200 release from 1982, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "overhead",
      "sports"
    ],
    "title": "RealSports Football",
    "year": "1982"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "November 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "realsports-soccer",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "RealSports Soccer is an Atari 5200 release from 1982, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "overhead",
      "sports"
    ],
    "title": "RealSports Soccer",
    "year": "1982"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "April 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "realsports-tennis",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "RealSports Tennis is an Atari 5200 release from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "overhead",
      "sports"
    ],
    "title": "RealSports Tennis",
    "year": "1983"
  },
  {
    "developer": [
      "Lucasfilm Games"
    ],
    "difficulty": "fair",
    "firstReleased": "1986",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "rescue-on-fractalus",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Rescue on Fractalus! is an Atari 5200 release from 1986, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari Corp."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Rescue on Fractalus!",
    "year": "1986"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "difficult",
    "firstReleased": "November 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "river-raid",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "River Raid is an Atari 5200 release from 1983, tagged as demanding, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "River Raid",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "First Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "road-runner",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Road Runner is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Road Runner",
    "year": "1984"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "March 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "robotron-2084",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Robotron: 2084 is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Robotron: 2084",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "First Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "satan-s-hollow",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Satan's Hollow is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Satan's Hollow",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "Third Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "scraper-caper",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Scraper Caper is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Big Five Software"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "overhead",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Scraper Caper",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "serpentine",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Serpentine is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Broderbund"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Serpentine",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "December 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "solar-fox",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Solar Fox is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Solar Fox",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "September 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "space-dungeon",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Space Dungeon is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Space Dungeon",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "October 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "space-invaders",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Space Invaders is an Atari 5200 release from 1982, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Space Invaders",
    "year": "1982"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "space-shuttle-a-journey-into-space",
    "isRomhack": false,
    "moods": [
      "contemplative",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Space Shuttle: A Journey into Space is an Atari 5200 release from 1984, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Space Shuttle: A Journey into Space",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "First Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "sport-goofy",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Sport Goofy is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Sport Goofy",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "August 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "springer",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Springer is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Tigervision"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Springer",
    "year": "1983"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "difficult",
    "firstReleased": "October 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "star-raiders",
    "isRomhack": false,
    "moods": [
      "contemplative",
      "arcade"
    ],
    "obscurity": "classic",
    "pitch": "Star Raiders is an Atari 5200 release from 1982, tagged as demanding, story-forward, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 4,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "rich",
    "tags": [
      "NA exclusive",
      "adventure",
      "rpg"
    ],
    "title": "Star Raiders",
    "year": "1982"
  },
  {
    "developer": [
      "Sega"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "star-trek-strategic-operations-simulator",
    "isRomhack": false,
    "moods": [
      "contemplative",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Star Trek: Strategic Operations Simulator is an Atari 5200 release from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Sega"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Star Trek: Strategic Operations Simulator",
    "year": "1983"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "difficult",
    "firstReleased": "February 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "star-wars-return-of-the-jedi-death-star-battle",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Star Wars: Return of the Jedi Death Star Battle is an Atari 5200 release from 1984, tagged as demanding, lightly narrative, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 4,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "some",
    "tags": [
      "NA exclusive",
      "licensed character",
      "overhead"
    ],
    "title": "Star Wars: Return of the Jedi Death Star Battle",
    "year": "1984"
  },
  {
    "developer": [
      "Parker Brothers"
    ],
    "difficulty": "fair",
    "firstReleased": "June 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "star-wars-the-arcade-game",
    "isRomhack": false,
    "moods": [
      "heroic",
      "arcade"
    ],
    "obscurity": "strange",
    "pitch": "Star Wars: The Arcade Game is an Atari 5200 release from 1984, tagged as balanced, lightly narrative, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 3,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "some",
    "tags": [
      "NA exclusive",
      "licensed character",
      "overhead"
    ],
    "title": "Star Wars: The Arcade Game",
    "year": "1984"
  },
  {
    "developer": [
      "Atari, Inc."
    ],
    "difficulty": "fair",
    "firstReleased": "October 1982",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "super-breakout",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Super Breakout is an Atari 5200 release from 1982, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari",
      "Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Super Breakout",
    "year": "1982"
  },
  {
    "developer": [
      "Roklan Corporation"
    ],
    "difficulty": "fair",
    "firstReleased": "May 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "super-cobra",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Super Cobra is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Super Cobra",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "September 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "tac-scan",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Tac-Scan is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Sega"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Tac-Scan",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "August 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "tempest",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Tempest is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Tempest",
    "year": "1984"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "August 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "the-activision-decathlon",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "The Activision Decathlon is an Atari 5200 release from 1984, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 2,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "The Activision Decathlon",
    "year": "1984"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "May 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "the-dreadnaught-factor",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "The Dreadnaught Factor is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "The Dreadnaught Factor",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "December 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "toy-bizarre",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Toy Bizarre is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and platformer-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "platformer",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 2,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Toy Bizarre",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "August 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "track-and-field",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Track & Field is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Track & Field",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "Fourth Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "tutankham",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Tutankham is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Parker Brothers"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Tutankham",
    "year": "1984"
  },
  {
    "developer": [
      "GCC"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "vanguard",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Vanguard is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Vanguard",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "Second Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "warp-wars",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Warp Wars is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "overhead",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Warp Wars",
    "year": "1984"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "November 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "wing-war",
    "isRomhack": false,
    "moods": [
      "contemplative",
      "weird"
    ],
    "obscurity": "strange",
    "pitch": "Wing War is an unreleased Atari 5200 project from 1983, tagged as balanced, play-first, and top down-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "top-down",
    "publisher": [
      "Imagic"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 2,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "overhead",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Wing War",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "First Quarter 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "wings",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Wings is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 0,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Wings",
    "year": "1984"
  },
  {
    "developer": [
      "Roklan Corporation"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1983",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "wizard-of-wor",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Wizard of Wor is an Atari 5200 release from 1983, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "CBS Electronics"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Wizard of Wor",
    "year": "1983"
  },
  {
    "developer": [],
    "difficulty": "fair",
    "firstReleased": "March 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "xevious",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Xevious is an unreleased Atari 5200 project from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Atari, Inc."
    ],
    "regions": [
      "unreleased"
    ],
    "signalScore": 1,
    "sourceCategory": "unreleased",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "action",
      "unreleased",
      "unreleased exclusive"
    ],
    "title": "Xevious",
    "year": "1984"
  },
  {
    "developer": [
      "Sega"
    ],
    "difficulty": "fair",
    "firstReleased": "August 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "zaxxon",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Zaxxon is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Sega"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 1,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action",
      "shooter"
    ],
    "title": "Zaxxon",
    "year": "1984"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "zenji",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Zenji is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Zenji",
    "year": "1984"
  },
  {
    "developer": [
      "Activision"
    ],
    "difficulty": "fair",
    "firstReleased": "October 1984",
    "generatedAt": "2026-07-06T15:28:17.679Z",
    "id": "zone-ranger",
    "isRomhack": false,
    "moods": [
      "arcade",
      "heroic"
    ],
    "obscurity": "strange",
    "pitch": "Zone Ranger is an Atari 5200 release from 1984, tagged as balanced, play-first, and side scroller-leaning for the recommender.",
    "platform": "atari-5200",
    "playStyle": "side-scroller",
    "publisher": [
      "Activision"
    ],
    "regions": [
      "NA"
    ],
    "signalScore": 0,
    "sourceCategory": "licensed",
    "sourceUrl": "https://en.wikipedia.org/wiki/List_of_Atari_5200_games",
    "story": "low",
    "tags": [
      "NA exclusive",
      "action"
    ],
    "title": "Zone Ranger",
    "year": "1984"
  }
];
